### ISSUE TITLE
Remote I/O error. Failed to write to I2C Slave 0x8 @ [write_byte():write 121], Could not read from I2C slave 0x8, [read_byte():read 121]

### ISSUE THREAD

**Issue by vijaybande** [bandasaikrishna/Autonomous_Mobile_Robot#5]
I am gettig below errros while running controller_check.launch. i2c slaves 0x08 and 0x09 were detected on Rpi

[ERROR] [1617861674.244743164]: Could not read from I2C slave 0x8, [read_byte():read 121]
[ERROR] [1617861674.252197838]: Could not read from I2C slave 0x9, [read_byte():read 121]
[ERROR] [1617861674.252879451]: Remote I/O error. Failed to write to I2C Slave 0x8 @ [write_byte():write 121]
[ERROR] [1617861674.253275023]: Remote I/O error. Failed to write to I2C Slave 0x9 @ [write_byte():write 121]
[ERROR] [1617861674.344301937]: Could not read from I2C slave 0x8, [read_byte():read 121]
[ERROR] [1617861674.345627664]: Could not read from I2C slave 0x9, [read_byte():read 121]
[ERROR] [1617861674.444579302]: Could not read from I2C slave 0x8, [read_byte():read 121]
[ERROR] [1617861674.446186018]: Could not read from I2C slave 0x9, [read_byte():read 121]
[ERROR] [1617861674.544354689]: Could not read from I2C slave 0x8, [read_byte():read 121]
[ERROR] [1617861674.546916455]: Could not read from I2C slave 0x9, [read_byte():read 121]
[ERROR] [1617861674.644397524]: Could not read from I2C slave 0x8, [read_byte():read 121]
[ERROR] [1617861674.645817938]: Could not read from I2C slave 0x9, [read_byte():read 121]
[ERROR] [1617861674.744349213]: Could not read from I2C slave 0x8, [read_byte():read 121]

**Comment by vijaybande** [comment]
Resolved.

**Comment by audricsaragih** [comment]
Could you tell me please how you solved this?

**Comment by vijaybande** [comment]
1.) Make sure that the both i2c are enabled on the board i.e i2c-0 and i2c-
1
2.) Connect the arduino slave 08 to i2c-0 and arduino slave 09 to i2c-1

But may I know how it is working in the link given below ??
https://youtu.be/Uz_i_sjVhIM

**Comment by audricsaragih** [comment]
Yes I've done that both.
But when i run :

> i2cdetect -y 0

or

> i2cdetect -y 1

It didn't catch any adress
I'm stuck there too

**Comment by vijaybande** [comment]
Are u using raspberry pi or Jetson nano??

**Comment by vijaybande** [comment]
Can we connect over the call??

**Comment by audricsaragih** [comment]
I'm using Raspberry Pi.
Sure, you can email me first at audric.saragih@gmail.com

**Comment by robotos2023** [comment]
I got the same error. I am using Raspberry pi 4 model b. Can you please tell me how you do it? I'd appreciate it a lot!

**Comment by jomar04** [comment]
Can I ask how you resolve it?

**Comment by Rithikrkm** [comment]
Bro Im having the same issue and I've been stuck here for a while, can you pls share how u resolved this issue
