### ISSUE TITLE
Navigation without encoder

### ISSUE THREAD

**Issue by mehmetaksu2034** [bandasaikrishna/Autonomous_Mobile_Robot#6]
Hi, thanks for sharing this nice project. can I use yours navigation stack in my robot that has not any encoder?

**Comment by mehmetaksu2034** [comment]
Yes, it is possible.

**Comment by Kuhan96** [comment]
@mehmetaksu2034 
Hello can I know how you perform this without using motor with encoders? thank you

**Comment by mehmetaksu2034** [comment]
I used laser scan matcher technique for gmapping and localisation (amcl). Then I changed the config file that shared here according to its own robot. And finally, by running the move_base.launch file, I can make the navigation process.
